#!/bin/bash

# A "Here" bash script to create a basic HTML page

cat <<-_EOF_
<HTML>
<HEAD>
  <TITLE> here comes the title of your page</TITLE>
</HEAD>
<BODY>
 Your page body comes here
</BODY>
</HTML>
_EOF_

